name: Update Real Estate Data

on:
  push:  # Push 이벤트가 발생할 때 실행
    branches:
      - main  # main 브랜치에 변경 사항이 있을 때만 실행
  schedule:  # 매일 자정(UTC)에 실행
    - cron: "0 0 * * *"
  workflow_dispatch:  # 수동 실행을 위한 트리거

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Data Update Script
      run: python naver_real_state.py
      working-directory: /home/runner/work/real_estate_project/real_estate_project
